- name: Import roles
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - fedora.linux_system_roles.aide
    - fedora.linux_system_roles.firewall
    - fedora.linux_system_roles.network
    - fedora.linux_system_roles.selinux
    - fedora.linux_system_roles.sshd
    - fedora.linux_system_roles.timesync
